decks:
- name: devdeck.decks.single_page_deck_controller.SinglePageDeckController
  serial_number: AB3MA5152IYH
  settings:
    controls:
    - key: 0
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Ketron\nEVM
        font_size: 100
        color: white
        background_color: ketron_blue
    - key: 1
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Intro/\nEnd1
        font_size: 100
        color: white
        background_color: green
    - key: 2
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Intro/\nEnd2
        font_size: 100
        color: white
        background_color: green
    - key: 3
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Intro/\nEnd3
        font_size: 100
        color: white
        background_color: green
    - key: 4
      name: devdeck.controls.text_control.TextControl
      settings:
        text: To End
        font_size: 100
        color: white
        background_color: red
    - key: 5
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Arr.A
        font_size: 100
        color: white
        background_color: blue
    - key: 6
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Arr.B
        font_size: 100
        color: white
        background_color: blue
    - key: 7
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Arr.C
        font_size: 100
        color: white
        background_color: blue
    - key: 8
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Arr.D
        font_size: 100
        color: white
        background_color: blue
    - key: 9
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Variat\nion
        font_size: 100
        color: white
        background_color: blue
    - key: 14
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Start/\nStop
        font_size: 100
        color: white
        background_color: red
    - key: 11
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Half\nBar
        font_size: 100
        color: black
        background_color: lightgreen
    - key: 12
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Fill
        font_size: 100
        color: white
        background_color: green
    - key: 13
      name: devdeck.controls.text_control.TextControl
      settings:
        text: Break
        font_size: 100
        color: white
        background_color: orange
    - key: 10
      name: devdeck.controls.navigation_toggle_control.NavigationToggleControl
      settings:
        icon: ''
        background_color: grey
        text_color: black
        target_deck_class: devdeck.decks.second_page_deck_controller.SecondPageDeckController
        target_deck_settings:
          controls:
          - key: 0
            name: devdeck.controls.text_control.TextControl
            settings:
              text: Dial\nUp
              font_size: 100
              color: white
              background_color: blue
          - key: 1
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 2
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 3
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 4
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 5
            name: devdeck.controls.text_control.TextControl
            settings:
              text: Dial\nDown
              font_size: 100
              color: white
              background_color: blue
          - key: 6
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 7
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 8
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 9
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 14
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 11
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 12
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 13
            name: devdeck.controls.text_control.TextControl
            settings:
              text: ''
              font_size: 100
              color: white
              background_color: black
          - key: 10
            name: devdeck.controls.navigation_toggle_control.NavigationToggleControl
            settings:
              icon: ''
              background_color: grey
              text_color: black
